{% set version = "1.8.1" %}

package:
  name: tensorboard-plugin-wit
  version: {{ version }}

source:
  url: https://pypi.io/packages/py3/t/tensorboard-plugin-wit/tensorboard_plugin_wit-{{ version }}-py3-none-any.whl
  sha256: ff26bdd583d155aa951ee3b152b3d0cffae8005dc697f72b44a8e8c2a77a8cbe

build:
  number: 0
  noarch: python
  script:
    - python -m pip install --no-deps --ignore-installed tensorboard_plugin_wit-{{ version }}-py3-none-any.whl

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - tensorboard_plugin_wit

about:
  home: https://pair-code.github.io/what-if-tool
  license: Apache-2.0
  license_file: LICENSE
  summary: An easy-to-use interface for expanding understanding of a black-box classification or regression ML model

extra:
  recipe-maintainers:
    - jschueller
