{% set version = "1.8.0" %}

package:
  name: tensorboard-plugin-wit
  version: {{ version }}

source:
  url: https://pypi.io/packages/py3/t/tensorboard-plugin-wit/tensorboard_plugin_wit-{{ version }}-py3-none-any.whl
  sha256: 2a80d1c551d741e99b2f197bb915d8a133e24adb8da1732b840041860f91183a

build:
  number: 0
  noarch: python
  script:
    - python -m pip install --no-deps --ignore-installed tensorboard_plugin_wit-{{ version }}-py3-none-any.whl

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - tensorboard_plugin_wit

about:
  home: https://pair-code.github.io/what-if-tool
  license: Apache-2.0
  license_file: LICENSE
  summary: An easy-to-use interface for expanding understanding of a black-box classification or regression ML model

extra:
  recipe-maintainers:
    - jschueller
